src/documents/hack/cookbooks/data-system-odm.html.md
=> Correct typo on data-system-odm

src/documents/hack/getting-started/learn-single-page-app-way.html.md
Getting started with a single page app now mentions the `cozy-dev new
<appname>` functionality (affects #42).
=> Added note about cozy-dev scaffolding feature.

README.md
…and automatically trimmed some blanks at line ends. If you are just getting started like me, you neither know docpad nor have it installed (or the jade plugin, which is not bundled with docpad). Pointing that out shortens the time between cloning and pull request.
=> Expanded the section about how to build the docs.

src/documents/hack/cookbooks/authentication-authorization-workflows.html.md, src/documents/hack/cookbooks/components.html.md, src/documents/hack/cookbooks/debugging-production.html.md, src/documents/hack/cookbooks/encryption.html.md, src/documents/hack/cookbooks/index.html.md, src/documents/hack/cookbooks/nodemon-server-auto-refresh-on-change.html.md, src/documents/host/manage.html.md
=> Update cozy-monitor documentation

src/layouts/fr/homepage.html.jade
We should put the sign me up part after the About us section.
=> Second pass of the French version.

src/documents/en/hack/releases/patch-notes-1.html.jade, src/layouts/en/homepage.html.jade, src/layouts/fr/homepage.html.jade
I think there are no french version at this moment
=> Fix en/hack/getting-started/ in FR version

src/layouts/fr/homepage.html.jade
=> Fix typo on french homepage

src/documents/fr/host/install.html.md, src/documents/fr/host/manage.html.md, src/documents/fr/host/trouble-shootings.html.md, src/documents/fr/host/uninstall.html.md, src/documents/fr/mobile/calendar.html.md, src/documents/fr/mobile/contacts.html.md
Hello
Voici quelques corrections de la doc française :smiley:
=> Fix some typo in fr content

src/documents/en/host/install.html.md, src/documents/fr/host/install.html.md
=> English version of Apache configuration

src/documents/en/hack/cookbooks/understanding-dev-environment.html.md, src/documents/en/host/install.html.md, src/documents/en/mobile/files.html.md, src/documents/fr/host/install.html.md, src/documents/fr/mobile/files.html.md
* Add mobile requirement ('files' application should installed)
* Correct update-image command
* VM should started before update it
* Frabic should be installed on local machine to reset security token
=> Some little improvements 

src/documents/host/trouble-shootings.html.md
Added some infos about what I bumped into during my first installations.
Will show in http://cozy.io/en/host/trouble-shootings.html
=> doc(troubleshooting): added some infos about VM troubles

src/documents/en/host/install.html.md, src/documents/fr/host/install.html.md
Covers certificate generation, vhost configuration, DavDroid special case
=> doc(installation): added instructions to use one's own nginx server

src/documents/assets/css/home.css.styl
I fixed the font-size for screens less wide than 480px and removed the parrallax effect when the screen is less wide than 600px.
=> Improve mobile styles

src/documents/en/hack/getting-started/first-app.html.md
Hi,
While doing this tutorial, I noticed that written as it is it does not work. Maybe this is due to some Express 3.x versus 4.x changes.
Anyway, in this commit you will find the code that make this first app works with Express 4.12.3.
=> modify incorrect codes, maybe due to changes between Express 3.x and 4.x

src/layouts/fr/homepage.html.jade
`<osef>` là où l'anglais écrit "beta version" le français écrit "version bêta" avec un accent (http://www.cnrtl.fr/lexicographie/b%C3%AAta) `</osef>`
=> typofixing

src/documents/en/mobile/calendar.html.md, src/documents/en/mobile/contacts.html.md, src/documents/fr/mobile/calendar.html.md, src/documents/fr/mobile/contacts.html.md
Picture os steps are missing because I don't know how to upload them. I send them to Frank.
=> Add OSX to contacts and calendar apps

src/documents/en/mobile/calendar.html.md, src/documents/fr/mobile/calendar.html.md
some "" forgotten and I add a click "next" and "continuez".
=> small changes

src/documents/en/hack/cookbooks/deploy.html.md, src/documents/en/hack/getting-started/discover-americano.html.md, src/documents/en/host/install/install-on-debian.html.md, src/documents/en/host/install/install-on-ubuntu.html.md, src/documents/en/mobile/calendar.html.md, src/documents/fr/host/install/install-on-debian.html.md, src/documents/fr/host/install/install-on-ubuntu.html.md, src/documents/fr/mobile/calendar.html.md
A contribution from our user Aleth Gueguen
=> Explain how to sync an existing calendar

src/documents/assets/css/main.css.styl, src/documents/en/hack/getting-started/architecture-overview.html.md, src/documents/en/hack/getting-started/learn-single-page-app-way.html.md, src/documents/en/hack/getting-started/play-with-data-system.html.md, src/documents/en/hack/getting-started/setup-environment.html.md
Check the commits for any explanatory notes. And let me know if you don't understand why I changed something, or if there are any problems.
=> Proofreading the "Getting Started" developer docs.

src/documents/en/hack/getting-started/first-app.html.md
Add more explanation about Cozy Light and the purpose of the first action.
=> Improve introduction for the first step of the tutorial

src/documents/en/hack/releases/index.html.md, src/documents/en/hack/releases/patch-notes-1.html.jade, src/documents/en/hack/releases/patch-notes-10.html.jade, src/documents/en/hack/releases/patch-notes-11.html.jade, src/documents/en/hack/releases/patch-notes-12.html.jade, src/documents/en/hack/releases/patch-notes-2.html.jade, src/documents/en/hack/releases/patch-notes-3.html.jade, src/documents/en/hack/releases/patch-notes-4.html.jade, src/documents/en/hack/releases/patch-notes-5.html.jade, src/documents/en/hack/releases/patch-notes-6.html.jade, src/documents/en/hack/releases/patch-notes-7.html.jade, src/documents/en/hack/releases/patch-notes-8.html.jade, src/documents/en/hack/releases/patch-notes-9.html.jade
I'm pretty sure lot of things are missing in this release note.
=> Add release note #12

src/documents/en/hack/getting-started/setup-environment.html.md
Fixed some typos in the documentation.
=> Fixed typos

src/documents/en/hack/getting-started/discover-americano.html.md, src/documents/en/hack/getting-started/setup-environment.html.md
=> Added CoffeeLint to dev packages needed (optional)

src/layouts/en/default.html.jade, src/layouts/en/homepage.html.jade, src/layouts/en/single-page.html.jade, src/layouts/fr/default.html.jade, src/layouts/fr/homepage.html.jade, src/layouts/fr/single-page.html.jade
The CNIL is not friendly with cookies :-)
=> [enh] Disable cookies for tracking

README.md, src/documents/en/hack/cookbooks/controller.html.md, src/documents/en/host/install/install-on-debian.html.md, src/documents/en/host/install/install-on-ubuntu.html.md, src/documents/en/host/manage.html.md, src/documents/fr/host/install/install-on-debian.html.md, src/documents/fr/host/manage.html.md
=> Fix glitches

src/documents/en/hack/getting-started/setup-environment.html.md
=> Fixing typo

src/documents/en/hack/cookbooks/components.html.md, src/documents/en/host/diagnose.html.md, src/documents/en/host/install/index.html.md, src/documents/en/host/install/install-step-by-step.html.md, src/documents/en/host/manage.html.md, src/documents/fr/host/diagnose.html.md, src/documents/fr/host/install/index.html.md, src/documents/fr/host/manage.html.md
@aenario, what do you think about it in src/documents/en/hack/cookbooks/data-system.html.md & src/documents/en/hack/getting-started/architecture-overview.html.md?
=> Remove indexer

src/documents/en/host/install/install-on-archlinux.html.md, src/documents/fr/host/install/install-on-archlinux.html.md
After having experienced the archlinux `cozy-apache` installation, I thought a few things needed to be made more precise. Here is the corresponding PR.
What do you think about that @babolivier ?
=> Make archlinux installation a little bit more precise

src/documents/en/hack/releases/patch-notes-17.html.jade, src/documents/en/hack/releases/patch-notes-18.html.jade
@jsilvestre I have a little question: the /hack part having been removed from the documentation, where will the release notes be published?
=> Patch note #18

src/documents/en/host/install/install-on-debian.html.md, src/documents/fr/host/install/install-on-debian.html.md
=> Add installation of npm 2 in Debian tutorial

src/documents/en/host/install/install-on-debian.html.md, src/documents/en/host/install/install-on-ubuntu.html.md
=> Fixed typo in Debian / Ubuntu docs

src/documents/en/host/install/install-on-debian.html.md, src/documents/en/host/install/install-on-digitalocean.html.md, src/documents/en/host/install/install-on-ubuntu.html.md, src/documents/fr/host/install/install-on-debian.html.md, src/documents/fr/host/install/install-on-digitalocean.html.md, src/documents/fr/host/install/install-on-ubuntu.html.md
With publishing on docs.cozy.io thanks.
=> Update with new Debian packaging

src/documents/en/host/install/index.html.md, src/documents/fr/host/install/index.html.md
Currently the install section is splitted in several parts which are a little bit confusing. I merged the *on your hardware*, *on your system* and *step by step* parts to make things simpler.
=> Make install section simpler

src/documents/en/host/install/install-on-virtualbox.html.md, src/documents/fr/host/install/install-on-virtualbox.html.md
=> Network access for VirtualBox image

src/documents/en/host/install/install-on-virtualbox.html.md, src/documents/fr/host/install/install-on-virtualbox.html.md
Wrong Cozy port and information about failed setup and way to restart new one.
=> More info for Virtualbox install

src/documents/en/host/install/install-on-virtualbox.html.md, src/documents/fr/host/install/install-on-virtualbox.html.md
@aeris Can you review it please?
=> Update Virtualbox documentation

src/documents/en/host/install/install-on-raspberry.html.md, src/documents/en/host/install/install-on-virtualbox.html.md, src/documents/fr/host/install/install-on-raspberry.html.md, src/documents/fr/host/install/install-on-virtualbox.html.md
It also includes a minor fix on the virtualbox page (broken link).
=> Update doc for Raspberry

src/documents/en/hack/cookbooks/authentication-authorization-workflows.html.md
=> Fix small tipo

src/documents/en/host/install/install-step-by-step.html.md
=> [step by step] Explain how to start supervisord

src/documents/en/host/install/install-step-by-step.html.md
=> Fixes on the step by step install

src/documents/en/mobile/desktop.html.md, src/documents/fr/mobile/desktop.html.md
This is a first update for the v3, I didn't ask the engagement team for the ton of voice and wording.
=> Improve user doc for Cozy Drive for desktop
